---
kind: pipeline
type: docker
name: default

steps:
  - name: initial
    image: node:12.10.0
    commands:
      - npm install

  - name: initial
    image: node:12.10.0
    commands:
      - npm run build

  - name: pack
    image: node:12.10.0
    commands:
      - tar zcvf dist.tar.gz dist/*

  - name: scp
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      port:
        from_secret: ssh_port
      user:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      target: $PROJECTS/dist.tar.gz
      source: dist.tar.gz

  - name: deloy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      port:
        from_secret: ssh_port
      user:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      script:
        - cd $PROJECTS
        - tar zxvf dist.tar.gz
        - mv dist ebook