---
kind: pipeline
type: docker
name: default
trigger:
  branch: master
  event: push
steps:
  - name: initial
    image: node:12.10.0
    commands:
      - npm install

  - name: build
    image: node:12.10.0
    commands:
      - npm run build

  - name: pack
    image: node:12.10.0
    commands:
      - tar zcvf dist.tar.gz dist/*

  - name: scp
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      port:
        from_secret: ssh_port
      user:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      target: /tmp/ebook
      source: dist.tar.gz
      rm: true

  - name: deloy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      port:
        from_secret: ssh_port
      user:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      script:
        - cd /tmp/ebook
        - tar zxvf dist.tar.gz
        - mv dist $PROJECTS/ebook